apiVersion: apps/v1
kind: Deployment
metadata: 
 name: webserver
 labels:
  app: nginx 
spec: 
 replicas: 3
 selector:
  matchlabels:
   app: nginx
 templates:
  metadata:
   labels:
    app: nginx
  spec:
   containers:
    - name: nginx
      image: nginx:alpine
      ports:
       - containerport: 80

 
